# Dockerfile - Build the container
FROM python:3.12-slim

WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
# COPY ./app .

# Expose port
EXPOSE 8088

# Run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8088", "--reload"]